In [55]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
file = pd.read_csv('mnist_train.csv')
data = file.copy()
data

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59997,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59999,8,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [69]:
test_file = pd.read_csv('mnist_test.csv')
test_data = test_file.copy()
test_data

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
data.iloc[:, 0].unique()

array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8], dtype=int64)

In [15]:
data[data['label'] == 0]

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59940,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59944,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59952,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59972,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59987,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
label_0 = data[data['label'] == 0]
cluster_0 = []
for i in range(1, 785):
    cluster_0.append(label_0.iloc[:, i].mean())

In [44]:
label_1 = data[data['label'] == 1]
cluster_1 = []
for i in range(1, 785):
    cluster_1.append(label_1.iloc[:, i].mean())

In [45]:
label_2 = data[data['label'] == 2]
cluster_2 = []
for i in range(1, 785):
    cluster_2.append(label_2.iloc[:, i].mean())

In [46]:
label_3 = data[data['label'] == 3]
cluster_3 = []
for i in range(1, 785):
    cluster_3.append(label_3.iloc[:, i].mean())

In [47]:
label_4 = data[data['label'] == 4]
cluster_4 = []
for i in range(1, 785):
    cluster_4.append(label_4.iloc[:, i].mean())

In [48]:
label_5 = data[data['label'] == 5]
cluster_5 = []
for i in range(1, 785):
    cluster_5.append(label_5.iloc[:, i].mean())

In [49]:
label_6 = data[data['label'] == 6]
cluster_6 = []
for i in range(1, 785):
    cluster_6.append(label_6.iloc[:, i].mean())

In [50]:
label_7 = data[data['label'] == 7]
cluster_7 = []
for i in range(1, 785):
    cluster_7.append(label_7.iloc[:, i].mean())

In [51]:
label_8 = data[data['label'] == 8]
cluster_8 = []
for i in range(1, 785):
    cluster_8.append(label_8.iloc[:, i].mean())

In [52]:
label_9 = data[data['label'] == 9]
cluster_9 = []
for i in range(1, 785):
    cluster_9.append(label_9.iloc[:, i].mean())

In [66]:
def distance(row, cluster):
    dist = 0
    for i in range(1, 784):
        dist += (row[i] - cluster[i-1])**2
    return math.sqrt(dist)

In [67]:
data.iloc[0][1]

0

In [68]:
distance(data.iloc[0], cluster_0)

2073.8304963947426

In [70]:
d = {'cluster_0': cluster_0,'cluster_1': cluster_1,'cluster_2': cluster_2,'cluster_3': cluster_3,'cluster_4': cluster_4,
  'cluster_5': cluster_5,
  'cluster_6': cluster_6,
  'cluster_7': cluster_7,
  'cluster_8': cluster_8,
  'cluster_9': cluster_9
}

In [83]:
def dist_point_name(row):
    dict_dist = {}
    for i in range(10):
        dict_dist[i] = distance(row, d['cluster_'+str(i)])
    return list(dict_dist.keys())[list(dict_dist.values()).index(min(dict_dist.values()))]

In [84]:
dist_point_name(test_data.iloc[0])

7

In [85]:
actual_values = []
predicted_values = []
for i in range(len(test_data)):
    predicted_values.append(dist_point_name(test_data.iloc[i]))
    actual_values.append(list(test_data.iloc[i])[0])

NameError: name 'test_points' is not defined